### ISSUE TITLE
Regarding your model's 100% accuracy

### ISSUE THREAD

**Issue by willsike1** [Pndwiga11/VCT-Match-Prediction#1]
Hey, I was just scrolling through Github when I found this repo, I'm currently attempting the same thing, but with a larger dataset.

Your model is achieving a 100% accuracy because the score data is being included in the training data, as well as with the test data, and the model has learnt to just predict the outcome based on the larger number.

I have tried training it solely on the team names (converted to IDs) and the outcome, and I seem to have it a hard barrier at around 62%, and I am unable to figure out why.

Thanks for your time, hope we can help each other.
- willsike69

**Comment by Pndwiga11** [comment]
Hi Willsike69,

Thanks for pointing that out about the 100% accuracy issue—I hadn’t noticed
it was because of the score data in training and testing. I’ve reworked the
model to predict scores instead, and it’s now starting at a more realistic
76% accuracy.

Your project with the larger dataset sounds awesome, and I hope you figure
out why it’s hitting that 62% barrier. Let me know if you come across
anything useful—I’d be happy to share any insights I find as well.

Thanks again for reaching out!

Best,
Pndwiga11

**Comment by willsike1** [comment]
Hey, I was having a look at potential extra data points to add, and I had an idea to use previous matchups of a given team in the data (i.e head to head) data on vlr.gg but cannot figure out how to implement this. 

If this could be included, I would bet that the training accuracy would increase quite a bit.

Thanks for the earlier reply!

Best regards,
willsike69
